//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apidracotheca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livro
    {
        public int tombo { get; set; }
        public string nome { get; set; }
        public string autor { get; set; }
        public Nullable<int> edicao { get; set; }
    }
}
